services:
  frontend:
    build: .
    container_name: crypto-frontend
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3002
      - NEXT_PUBLIC_AUTH_URL=http://localhost:3006
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3005
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - crypto_network

networks:
  crypto_network:
    name: crypto_network
    external: true 